# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: AuthorAI
email: authorai.org@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  At AuthorAI we want to reimagine the authoring experience powered by AI. 
  We want to explore how state of the art in AI can evolve the authoring flow
  as it applies to creating apps, books, blogs, sites, data, designs, reports, and more.

baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: AuthorAIorg
github_username:  authorai

domain: authorai.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://authorai.github.io  # the base hostname and protocol for your site, e.g. http://example.com

# GitHub Pages defaults
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Build settings
theme: minima
plugins:
  - jekyll-feed

excerpt_separator: <!--more-->
show_excerpts: true

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
